baseURL = "https://www.jibbow.com/"
languageCode = "en-us"
title = "Jibbow's Blog"

theme = "tale"

# Configure code blocks
pygmentsCodeFences = true
pygmentsStyle = "xcode"

[Params]
Author = "Andreas"
