baseURL = "https://www.jibbow.com/"
languageCode = "en-us"
title = "Jibbow's Blog"

theme = "tale"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 2

[Params]
Author = "Andreas"
