baseURL = "https://andizimmerer.github.io/"
title = "Andi Zimmerer"
languageCode = "en-us"
googleAnalytics = "UA-165398559-1"
theme = "jib"


[params]

# Config options about the website itself, used mostly to generate meta information about the blog.
[params.website]
author = "Andi Zimmerer"
description = "Technical explorations of database systems research, focusing on architecture, optimization, and system design through the lens of doctoral research."
keywords = "Databases, Data Warehouses, Systems Programming, Rust, C++"
headertitle = "Database Systems Research"
preview_image = "site_preview_image.jpg"


# directory containing static resources that are published as-is.
# Available under https://www.jibbow.com/<filename>
staticDir = ['static']

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2


[[params.social]]
title = "LinkedIn"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/andi-zimmerer/"

[[params.social]]
title = "Let's use Bluesky from now on"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://bsky.app/profile/andizimmerer.bsky.social"

[[params.social]]
title = "GitHub"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/andizimmerer"

[[params.social]]
title = "Subscribe via RSS"
icon = "ti-rss" # themify icon : https://themify.me/themify-icons
link = "/index.xml"
