baseURL = "https://www.jibbow.com/"
title = "Jibbow's Blog (by Andreas Zimmerer)"
languageCode = "en-us"
googleAnalytics = "UA-165398559-1"
theme = "jib"


[params]

# Config options about the website itself, used mostly to generate meta information about the blog.
[params.website]
author = "Andreas Zimmerer"
description = "Jibbows' blog about computerology written and published by Andreas Zimmerer."
keywords = "Computers, Programming, Rust, C++, Systems"
headertitle = "Rather spend your time with something else..."
preview_image = "site_preview_image.jpg"


# directory containing static resources that are published as-is.
# Available under https://www.jibbow.com/<filename>
staticDir = ['static']

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2


[[params.social]]
title = "LinkedIn"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/andreas-zimmerer/"

[[params.social]]
title = "Follow me on Twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/_jibbow"

[[params.social]]
title = "GitHub"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/Jibbow"

[[params.social]]
title = "Stack Overflow"
icon = "ti-stack-overflow" # themify icon : https://themify.me/themify-icons
link = "https://stackoverflow.com/users/4777124/jibbow"

[[params.social]]
title = "Instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/andi.zimmerer"

[[params.social]]
title = "Subscribe via RSS"
icon = "ti-rss" # themify icon : https://themify.me/themify-icons
link = "/index.xml"
