baseURL = "https://www.jibbow.com/"
languageCode = "en-us"
title = "Jibbow's Blog"

theme = "jib"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

[params]
Author = "Andreas"



[[params.social]]
title = "Follow me on Twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/_jibbow"

[[params.social]]
title = "GitHub"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/Jibbow"

[[params.social]]
title = "LinkedIn"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/andreas-zimmerer/"

[[params.social]]
title = "Subscribe via RSS"
icon = "ti-rss" # themify icon : https://themify.me/themify-icons
link = "/index.xml"
